feat: update Tailscale Docker Compose configuration for pifive.

diff --git a/tailscales/pifive-tailscale.yml b/tailscales/pifive-tailscale.yml
--- a/tailscales/pifive-tailscale.yml
+++ b/tailscales/pifive-tailscale.yml
@@ -168,15 +168,15 @@ services:
         done
         echo "Tailscale is ready."
 
-        if [ -n "$RAW_SERVICES" ]; then
+        if [ -n "$$RAW_SERVICES" ]; then
           echo "Found services to advertise using RAW_SERVICES variable."
           # Remove single/double quotes and replace commas with spaces
-          CLEAN_SERVICES=$(echo "$RAW_SERVICES" | tr -d "\047\042" | tr "," " ")
+          CLEAN_SERVICES=$$(echo "$$RAW_SERVICES" | tr -d "\047\042" | tr "," " ")
           
-          for SERVICE in $CLEAN_SERVICES; do
-            if [ -z "$SERVICE" ]; then continue; fi
-            echo "Advertising service: $SERVICE"
-            docker exec tailscale tailscale serve advertise "svc:$SERVICE" || echo "Failed to advertise $SERVICE"
+          for SERVICE in $$CLEAN_SERVICES; do
+            if [ -z "$$SERVICE" ]; then continue; fi
+            echo "Advertising service: $$SERVICE"
+            docker exec tailscale tailscale serve advertise "svc:$$SERVICE" || echo "Failed to advertise $$SERVICE"
           done
         else
           echo "No RAW_SERVICES provided."
